# Используем базовый образ Nginx
FROM nginx:latest

# Копируем свой файл index.html в контейнер
COPY index.html /usr/share/nginx/html/

# Определяем порт, который будет использоваться веб-сервером
EXPOSE 80